apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: litmuschaos
  namespace: flux-system
spec:
  chart:
    spec:
      chart: litmus
      version: 2.10.1
      sourceRef:
        kind: HelmRepository
        name: litmuschaos
        namespace: flux-system
      valuesFiles:
        - values.yaml
  interval: 10m0s
  targetNamespace: litmus