apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  linkerd.io/inject: enabled

commonLabels:
  tier: infrastructure
  app: flux

resources:
  - gotk-components.yaml
  - gotk-sync.yaml

namespace: flux-system
