---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: monitoring-stack
  namespace: flux-system
spec:
  healthChecks:
  - kind: Deployment
    name: kube-prometheus-stack-operator
    namespace: monitoring
  - kind: Deployment
    name: kube-prometheus-stack-grafana
    namespace: monitoring
  - apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    name: kube-prometheus-stack
    namespace: monitoring
  interval: 10m0s
  path: ./manifests/monitoring/kube-prometheus-stack
  prune: true
  sourceRef:
    kind: GitRepository
    name: monitoring
  timeout: 2m0s
  dependsOn:
    - name: kyverno-policies
