---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: flux-system
spec:
  interval: 1h0m0s
  timeout: 10m0s
  releaseName: loki
  targetNamespace: monitoring
  dependsOn:
    - name: kube-prometheus-stack
    - name: promtail
  chart:
    spec:
      chart: loki-distributed
      version: 0.54.0
      sourceRef:
        kind: HelmRepository
        name: grafana
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    ingester:
      nodeSelector:
        role: observability
    distributor:
      nodeSelector:
        role: observability
    querier:
      nodeSelector:
        role: observability
    queryFrontend:
      nodeSelector:
        role: observability
    gateway:
      nodeSelector:
        role: observability
