apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: giantswarm
  namespace: flux-system
spec:
  interval: 10m
  url: https://giantswarm.github.io/giantswarm-catalog

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: starboard-exporter
  namespace: flux-system
spec:
  chart:
    spec:
      chart: starboard-exporter
      version: 0.4.1
      sourceRef:
        kind: HelmRepository
        name: giantswarm
        namespace: flux-system
      valuesFiles:
        - values.yaml
  interval: 10m0s
  targetNamespace: starboard-system
  dependsOn:
    - name: starboard-operator