apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  linkerd.io/inject: disabled

commonLabels:
  tier: tools

resources:
  - https://litmuschaos.github.io/litmus/2.4.0/litmus-2.4.0.yaml

patchesStrategicMerge:
  - patches/load-balancer.yaml
  - patches/server-cluster-ip.yaml

namespace: litmus
