apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: litmuschaos
  namespace: flux-system
spec:
  interval: 1h0m0s
  timeout: 10m0s
  targetNamespace: litmus
  chart:
    spec:
      chart: litmus
      version: 2.10.1
      sourceRef:
        kind: HelmRepository
        name: litmuschaos
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    customLabels:
      tier: tools
    upgradeAgent:
      nodeSelector:
        role: tools
    portal:
      frontend:
        nodeSelector:
          role: tools
      server:
        nodeSelector:
          role: tools
    mongo:
      nodeSelector:
        role: tools
