apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: aquasecurity
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://aquasecurity.github.io/helm-charts/

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: starboard-operator
  namespace: flux-system
spec:
  chart:
    spec:
      chart: starboard-operator
      version: 0.10.4
      sourceRef:
        kind: HelmRepository
        name: aquasecurity
        namespace: flux-system
      valuesFiles:
        - values.yaml
  interval: 10m0s
  targetNamespace: starboard-system