---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting
  namespace: emojivoto
spec:
  template:
   spec:
      containers:
        - name: voting-svc
          securityContext:
            readOnlyRootFilesystem: true

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: emojivoto
spec:
  template:
   spec:
      containers:
        - name: web-svc
          securityContext:
            readOnlyRootFilesystem: true

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emoji
  namespace: emojivoto
spec:
  template:
   spec:
      containers:
        - name: emoji-svc
          securityContext:
            readOnlyRootFilesystem: true

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-bot
  namespace: emojivoto
spec:
  template:
   spec:
      containers:
        - name: vote-bot
          securityContext:
            readOnlyRootFilesystem: true


