---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting
  namespace: emojivoto
spec:
  template:
   spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      containers:
        - name: voting-svc
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: emojivoto
spec:
  template:
   spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      containers:
        - name: web-svc
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emoji
  namespace: emojivoto
spec:
  template:
   spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      containers:
        - name: emoji-svc
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-bot
  namespace: emojivoto
spec:
  template:
   spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      containers:
        - name: vote-bot
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false

