apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: litmuschaos
  namespace: flux-system
spec:
  interval: 10m
  url: https://litmuschaos.github.io/litmus-helm/

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: litmuschaos
  namespace: flux-system
spec:
  chart:
    spec:
      chart: litmus
      version: 2.8.0
      sourceRef:
        kind: HelmRepository
        name: litmuschaos
        namespace: flux-system
  interval: 10m0s
  targetNamespace: litmus