apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: gatekeeper-library
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/open-policy-agent/gatekeeper-library/
  ref:
    branch: master
  ignore: |
    # exclude all
    /*
    # include required directory
    !/library/
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: gatekeeper-library
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./library
  prune: true
  sourceRef:
    kind: GitRepository
    name: gatekeeper-library
  targetNamespace: gatekeeper-system
  dependsOn:
    - name: gatekeeper