---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: policy
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./infrastructure/policy
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
  healthChecks:
    - kind: Deployment
      name: kyverno
      namespace: kyverno
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: kyverno
      namespace: flux-system
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: kyverno-policies
      namespace: flux-system
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: policy-reporter
      namespace: flux-system
  dependsOn:
    - name: flux-system