apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: starboard-operator
  namespace: flux-system
spec:
  chart:
    spec:
      chart: starboard-operator
      version: 0.10.6
      sourceRef:
        kind: HelmRepository
        name: aquasecurity
        namespace: flux-system
      valuesFiles:
        - values.yaml
  interval: 10m0s
  targetNamespace: starboard-system