---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: loki
spec:
  interval: 1h0m0s
  path: ./k8s/infrastructure/source/monitoring/loki
  prune: true
  dependsOn:
    - name: prometheus-operator
  sourceRef:
    kind: GitRepository
    name: git-repo
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: loki
      namespace: flux-system
    - apiVersion: apps/v1
      kind: Deployment
      name: loki-gateway
      namespace: monitoring
    - apiVersion: apps/v1
      kind: Deployment
      name: loki-grafana-agent-operator
      namespace: monitoring
