---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: metallb
spec:
  interval: 1h0m0s
  path: ./k8s/infrastructure/source/metallb
  dependsOn:
    - name: policy
    - name: linkerd
  prune: true
  sourceRef:
    kind: GitRepository
    name: git-repo