apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: giantswarm
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://giantswarm.github.io/giantswarm-catalog
