apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kyverno
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://kyverno.github.io/kyverno/

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno
  namespace: flux-system
spec:
  chart:
    spec:
      chart: kyverno
      version: v2.3.3
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: flux-system
      interval: 40m
  timeout: 3m
  interval: 1h0m0s
  releaseName: kyverno
  targetNamespace: kyverno

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno-policies
  namespace: flux-system
spec:
  chart:
    spec:
      chart: kyverno-policies
      version: v2.3.4
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: flux-system
      interval: 40m
  timeout: 3m
  interval: 1h0m0s
  releaseName: kyverno-policies
  targetNamespace: kyverno
  dependsOn:
    - name: kyverno
