apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno-policies
  namespace: flux-system
spec:
  interval: 1h0m0s
  chart:
    spec:
      chart: kyverno-policies
      version: v2.3.4
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: flux-system
      interval: 40m
  targetNamespace: kyverno
  dependsOn:
    - name: kyverno
