---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kyverno
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/policy/kyverno
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system