---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kyverno
  namespace: flux-system
spec:
  interval: 1h0m0s
  path: ./infrastructure/policy/kyverno
  # dependsOn:
  #   - name: flux-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system