---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager
spec:
  interval: 1h0m0s
  path: ./infrastructure/source/cert-manager
  prune: true
  dependsOn:
    - name: policy
  sourceRef:
    kind: GitRepository
    name: git-repo
  validation: client
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: cert-manager
      namespace: cert-manager
    - apiVersion: apps/v1
      kind: Deployment
      name: cert-manager-cainjector
      namespace: cert-manager
    - apiVersion: apps/v1
      kind: Deployment
      name: cert-manager-webhook
      namespace: cert-manager
