---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: finalizers
spec:
  interval: 1h0m0s
  path: ./infrastructure/source/finalizers
  dependsOn:
    - name: linkerd
    - name: kyverno
    - name: kyverno-policies
    - name: cert-manager
    - name: metallb
    - name: ingress-nginx
    - name: prometheus-operator
    - name: metrics-server
  prune: true
  sourceRef:
    kind: GitRepository
    name: git-repo