---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ingress-nginx
spec:
  interval: 1h0m0s
  path: ./infrastructure/source/ingress-nginx
  dependsOn:
    - name: kyverno-policies
  prune: true
  sourceRef:
    kind: GitRepository
    name: git-repo
  validation: client
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: ingress-nginx-controller
      namespace: ingress-nginx
