---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kyverno-policies
spec:
  interval: 1h0m0s
  path: ./infrastructure/source/policy/kyverno-policies
  dependsOn:
    - name: kyverno
  prune: true
  sourceRef:
    kind: GitRepository
    name: git-repo