---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kyverno
  namespace: flux-system
spec:
  interval: 1h0m0s
  path: ./infrastructure/source/policy/kyverno
  prune: true
  dependsOn:
    - name: linkerd
  sourceRef:
    kind: GitRepository
    name: flux-system