---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: linkerd
  namespace: flux-system
spec:
  interval: 1h0m0s
  path: ./infrastructure/source/service-mesh/linkerd
  prune: true
  dependsOn:
    - name: kyverno
    - name: kyverno-policies
  sourceRef:
    kind: GitRepository
    name: flux-system
