---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: linkerd
spec:
  interval: 1h0m0s
  path: ./infrastructure/source/service-mesh/linkerd
  prune: true
  sourceRef:
    kind: GitRepository
    name: git-repo
