---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: flux-system
spec:
  interval: 1h0m0s
  targetNamespace: monitoring
  chart:
    spec:
      chart: loki-distributed
      version: 0.48.4
      sourceRef:
        kind: HelmRepository
        name: grafana
  install:
    crds: Create
  upgrade:
    crds: CreateReplace

