---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: flux-system
spec:
  interval: 1h0m0s
  releaseName: loki
  targetNamespace: monitoring
  chart:
    spec:
      chart: loki-simple-scalable
      version: 1.7.1
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
