---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: loki-stack
  namespace: flux-system
spec:
  interval: 1h0m0s
  path: ./infrastructure/source/monitoring/loki-stack
  dependsOn:
    - name: prometheus-operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
