---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 1h0m0s
  path: ./infrastructure/source/metallb
  dependsOn:
    - name: linkerd
    - name: kyverno
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system