---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/metallb
  dependsOn:
    - name: kyverno-policies
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system