---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  interval: 1h0m0s
  path: ./infrastructure/source/metrics-server
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system