apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: monitoring-stack
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./manifests/monitoring/kube-prometheus-stack
  prune: true
  sourceRef:
    kind: GitRepository
    name: monitoring
  patches:
    - patch: |-
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: not-used
        spec:
          template:
            spec:
              tolerations:
              - effect: NoSchedule
                key: role
                operator: Equal
                value: observability
  healthChecks:
  - kind: Deployment
    name: kube-prometheus-stack-operator
    namespace: monitoring
  - kind: Deployment
    name: kube-prometheus-stack-grafana
    namespace: monitoring
  - apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    name: kube-prometheus-stack
    namespace: monitoring

