---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: monitoring-stack
  namespace: flux-system
spec:
  interval: 1h0m0s
  path: ./infrastructure/source/monitoring/kube-prometheus-stack
  prune: true
  dependsOn:
    - name: linkerd
    - name: kyverno
  sourceRef:
    kind: GitRepository
    name: flux-system
