---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: policy
spec:
  interval: 1h0m0s
  path: ./infrastructure/source/policy
  prune: true
  dependsOn:
    - name: linkerd
  sourceRef:
    kind: GitRepository
    name: git-repo