apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: policy-reporter
  namespace: flux-system
spec:
  interval: 1h0m0s
  chart:
    spec:
      chart: policy-reporter
      version: 2.8.0
      sourceRef:
        kind: HelmRepository
        name: policy-reporter
        namespace: flux-system
  targetNamespace: policy-reporter
  values:
    kyvernoPlugin:
      enabled: true
    ui:
      enabled: true
      plugins:
        kyverno: true
