apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  interval: 10m0s
  targetNamespace: kube-system
  chart:
    spec:
      chart: sealed-secrets
      version: 2.1.8
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        namespace: flux-system
