apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  timeout: 3m
  interval: 1h0m0s
  releaseName: sealed-secrets
  targetNamespace: kube-system
  chart:
    spec:
      chart: sealed-secrets
      version: 2.1.8
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        namespace: flux-system
      interval: 40m
