apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  linkerd.io/inject: enabled

commonLabels:
  tier: infrastructure

resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.8.0/cert-manager.yaml

patchesStrategicMerge:
  - patches/resource-limits.yaml
  - patches/immutable-fs.yaml