---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tools
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./tools/manifests
  dependsOn:
    - name: finalizers
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: litmuschaos
      namespace: flux-system
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: starboard-operator
      namespace: flux-system
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: starboard-exporter
      namespace: flux-system
