---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tools
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./tools
  dependsOn:
    - name: finalizers
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system