---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: policy-reporter
  namespace: flux-system
spec:
  interval: 1h0m0s
  targetNamespace: policy-reporter
  timeout: 10m0s
  chart:
    spec:
      chart: policy-reporter
      version: 2.10.1
      sourceRef:
        kind: HelmRepository
        name: policy-reporter
      valuesFiles:
        - values.yaml
  install:
    crds: Create
    createNamespace: true
  upgrade:
    crds: CreateReplace