apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  linkerd.io/inject: enabled

commonLabels:
  app: emojivoto
  tier: application

resources:
# - resource
- emojivoto.yaml
- sync.yaml

patchesStrategicMerge:
  - patches/resource-limits.yaml
  - patches/immutable-fs.yaml