---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: emojivoto
spec:
  interval: 10m0s
  path: ./apps/emojivoto
  dependsOn:
    - name: finalizers
  prune: true
  sourceRef:
    kind: GitRepository
    name: git-repo
  validation: client
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: emoji
    - apiVersion: apps/v1
      kind: Deployment
      name: vote-bot
    - apiVersion: apps/v1
      kind: Deployment
      name: web
    - apiVersion: apps/v1
      kind: Deployment
      name: voting