---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
  namespace: flux-system
spec:
  interval: 1h0m0s
  targetNamespace: monitoring
  timeout: 10m0s
  dependsOn:
    - name: kube-prometheus-stack
  chart:
    spec:
      chart: promtail
      version: 6.3.0
      sourceRef:
        kind: HelmRepository
        name: grafana
  values:
    config:
      serverPort: 80
      clients:
        - url: http://loki-loki-distributed-gateway/loki/api/v1/push

