apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: linkerd
  tier: infrastructure

resources:
  - linkerd.yaml
  - priority-class.yaml

patchesStrategicMerge:
  - patches/resource-limits.yaml
  - patches/immutable-fs.yaml
  - patches/patch-priority-class.yaml

namespace: linkerd