---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkerd-identity
  namespace: linkerd
spec:
  template:
    spec:
      containers:
        - name: identity
          securityContext:
            readOnlyRootFilesystem: true

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkerd-destination
  namespace: linkerd
spec:
  template:
    spec:
      containers:
        - name: linkerd-proxy
          securityContext:
            readOnlyRootFilesystem: true

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkerd-proxy-injector
  namespace: linkerd
spec:
  template:
    spec:
      containers:
        - name: linkerd-proxy
          securityContext:
            readOnlyRootFilesystem: true

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: linkerd-heartbeat
  namespace: linkerd
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: heartbeat
              securityContext:
                readOnlyRootFilesystem: true

