---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: trivy-operator
spec:
  interval: 1h0m0s
  path: ./k8s/tools/source/trivy-operator
  prune: true
  timeout: 10m
  dependsOn:
    - name: policy
  sourceRef:
    kind: GitRepository
    name: git-repo
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: trivy-operator
      namespace: trivy-system
