apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: linkerd
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://helm.linkerd.io/stable

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-jaeger
  namespace: flux-system
spec:
  chart:
    spec:
      chart: linkerd-jaeger
      version: 2.11.2
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: flux-system
      interval: 40m
  timeout: 3m
  interval: 1h0m0s
  releaseName: linkerd-jaeger
  targetNamespace: linkerd-jaeger

