apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: starboard-operator
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://aquasecurity.github.io/helm-charts/

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: starboard-operator
  namespace: flux-system
spec:
  chart:
    spec:
      chart: starboard-operator
      version: 0.10.4
      sourceRef:
        kind: HelmRepository
        name: starboard-operator
        namespace: flux-system
      interval: 40m
  timeout: 3m
  interval: 1h0m0s
  releaseName: starboard-operator
  targetNamespace: starboard-system