apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/metallb/metallb//manifests?ref=v0.12.1
  - configmap.yaml

patchesStrategicMerge:
  - patches/resource-limits.yaml
  - patches/inject-linkerd.yaml
  