---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: finalizers
spec:
  interval: 1h0m0s
  path: ./k8s/infrastructure/source/finalizers
  prune: true
  timeout: 10m
  dependsOn:
    - name: linkerd
    - name: policy
    - name: cert-manager
    - name: sealed-secrets
    - name: metallb
    - name: ingress-nginx
    - name: monitoring
    - name: metrics-server
    - name: loki
  sourceRef:
    kind: GitRepository
    name: git-repo