---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ingress-nginx
spec:
  interval: 1h0m0s
  path: ./k8s/infrastructure/source/ingress-nginx
  dependsOn:
    - name: linkerd
  prune: true
  timeout: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: ingress-nginx-controller
      namespace: ingress-nginx
