apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - linkerd.yaml
  - policy.yaml
  - cert-manager.yaml
  - metallb.yaml
  - sealed-secrets.yaml
  - metrics-server.yaml
  - prometheus-operator.yaml
  - loki.yaml
  - ingress-nginx.yaml
  - finalizers.yaml

namespace: flux-system