---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: metrics-server
spec:
  interval: 1h0m0s
  path: ./k8s/infrastructure/source/metrics-server
  prune: true
  timeout: 10m
  dependsOn:
    - name: linkerd
  sourceRef:
    kind: GitRepository
    name: flux-system