---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: monitoring
  namespace: flux-system
spec:
  interval: 1h0m0s
  path: ./k8s/infrastructure/source/monitoring
  prune: true
  timeout: 10m
  dependsOn:
    - name: linkerd
  sourceRef:
    kind: GitRepository
    name: git-repo
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: kube-prometheus-stack
      namespace: monitoring
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: promtail
      namespace: monitoring
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: loki
      namespace: monitoring