---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: observability
spec:
  interval: 1h0m0s
  path: ./k8s/infrastructure/source/observability
  prune: true
  timeout: 10m
  dependsOn:
    - name: policy
  sourceRef:
    kind: GitRepository
    name: git-repo
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: policy-reporter
      namespace: policy-reporter