---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: sealed-secrets
spec:
  interval: 1h0m0s
  path: ./k8s/infrastructure/source/sealed-secrets
  prune: true
  timeout: 10m
  dependsOn:
    - name: policy
  sourceRef:
    kind: GitRepository
    name: git-repo
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: sealed-secrets
      namespace: flux-system