---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
spec:
  interval: 1h0m0s
  releaseName: sealed-secrets-controller
  targetNamespace: kube-system
  chart:
    spec:
      chart: sealed-secrets
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
      valuesFiles:
        - values.yaml
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
