---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
spec:
  interval: 1h0m0s
  timeout: 10m0s
  releaseName: loki
  targetNamespace: monitoring
  chart:
    spec:
      chart: loki-simple-scalable
      version: 1.8.0
      sourceRef:
        kind: HelmRepository
        name: grafana
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    serviceAccount:
      automountServiceAccountToken: false
