apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  linkerd.io/inject: enabled

commonLabels:
  app: ingress-nginx
  tier: infrastructure

resources:
  - https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml
  # - resource

patchesStrategicMerge:
  - patches/resource-limits.yaml
  - patches/immutable-fs.yaml

namespace: ingress-nginx
