---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: policy-reporter
  namespace: flux-system
spec:
  interval: 1h0m0s
  timeout: 10m0s
  targetNamespace: policy-reporter
  chart:
    spec:
      chart: policy-reporter
      version: 2.11.1
      sourceRef:
        kind: HelmRepository
        name: policy-reporter
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    kyvernoPlugin:
      enabled: true
    ui:
      enabled: true
      plugins:
        kyverno: true
    metrics:
      enabled: true
    monitoring:
      enabled: false
    rest:
      enabled: true
    resources:
      limits:
        memory: 100Mi
        cpu: 10m
      requests:
        memory: 75Mi
        cpu: 5m
    nodeSelector:
      role: observability