---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  interval: 1h0m0s
  timeout: 10m0s
  targetNamespace: monitoring
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 39.9.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
  values:
    prometheus:
      prometheusSpec:
        serviceMonitorSelectorNilUsesHelmValues: false
        serviceMonitorSelector: {}
        serviceMonitorNamespaceSelector: {}
        nodeSelector:
          role: observability

    grafana:
      sidecar:
        datasources:
          defaultDatasourceEnabled: true
      additionalDataSources:
        - name: Loki
          type: loki
          url: http://loki-loki-distributed-query-frontend.monitoring:3100

    alertmanagerSpec:
      nodeSelector:
        role: observability

    prometheusOperator:
      admissionWebhooks:
        patch:
          nodeSelector:
            role: observability
      nodeSelector:
        role: observability
