---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: trivy-operator
  namespace: flux-system
spec:
  interval: 1h0m0s
  path: ./tools/source/trivy-operator
  prune: true
  dependsOn:
    - name: kyverno-policies
  sourceRef:
    kind: GitRepository
    name: git-repo
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: trivy-operator
      namespace: trivy-system
