apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - cert-manager
  - finalizers
  - ingress-nginx
  - metallb
  - metrics-server
  - observability
  - policy
  # - sealed-secrets
  - service-mesh
