---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: gatekeeper
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./infrastructure/policy/gatekeeper
  # dependsOn:
  #   - name: infrastructure
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system