---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kyverno
spec:
  template:
    spec:
      containers:
        - name: kyverno
          resources:
            limits:
              memory: 384Mi
              cpu: 50m
            requests:
              memory: 256Mi
              cpu: 50m
