apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  linkerd.io/inject: enabled

commonLabels:
  tier: infrastructure

resources:
  - https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.18.1/controller.yaml
