---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
spec:
  interval: 1h0m0s
  timeout: 10m0s
  releaseName: sealed-secrets-controller
  targetNamespace: kube-system
  chart:
    spec:
      chart: sealed-secrets
      version: 2.5.2
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    commonAnnotations:
      linkerd.io/inject: disabled
    nodeSelector:
      role: worker
    resources:
      limits:
        memory: 384Mi
        cpu: 50m
      requests:
        memory: 256Mi
        cpu: 50m