---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 2m
  path: ./k8s/apps
  dependsOn:
    - name: linkerd
    - name: policy
  prune: true
  timeout: 10m
  wait: true
  sourceRef:
    kind: GitRepository
    name: git-repo

