---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: git-repo
  namespace: flux-system
spec:
  interval: 1h0m0s
  ref:
    branch: main
  timeout: 60s
  url: https://github.com/kevinobee/flux-example

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./k8s/infrastructure/manifests
  prune: true
  timeout: 10m
  sourceRef:
    kind: GitRepository
    name: git-repo
  healthChecks:
    - apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
      kind: Kustomization
      name: finalizers
      namespace: flux-system

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 1h0m0s
  path: ./k8s/apps
  dependsOn:
    - name: linkerd
    - name: policy
  prune: true
  timeout: 10m
  sourceRef:
    kind: GitRepository
    name: git-repo

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tools
  namespace: flux-system
spec:
  interval:  1h0m0s
  path: ./k8s/tools/manifests
  dependsOn:
    - name: linkerd
    - name: policy
  prune: true
  timeout: 10m
  sourceRef:
    kind: GitRepository
    name: git-repo
