---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tools
  namespace: flux-system
spec:
  interval:  1h0m0s
  path: ./k8s/tools
  dependsOn:
    - name: linkerd
    - name: policy
  prune: true
  timeout: 10m
  wait: true
  sourceRef:
    kind: GitRepository
    name: git-repo
