apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: podinfo
  tier: application

bases:
  - github.com/stefanprodan/podinfo//kustomize

resources:
  - namespace.yaml
  - sync.yaml

patchesStrategicMerge:
  - patches/immutable-fs.yaml

namespace: podinfo
