apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: kyverno
  tier: infrastructure

commonAnnotations:
  linkerd.io/inject: enabled

bases:
  - kyverno
  - kyverno-policies

namespace: kyverno
