replicas: 1
registry:
  domain: docker.io
image:
  name: "giantswarm/starboard-exporter"
  tag: "0.5.0"
pod:
  user:
    id: 1000
  group:
    id: 1000

nodeSelector: {}
tolerations: {}

# Pod securityContext
podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

# Container securityContext
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  privileged: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

resources:
  requests:
    cpu: 100m
    memory: 220Mi
  limits:
    cpu: 100m
    memory: 220Mi

project:
  branch: "HEAD"
  commit: "916210ae1f8ab844922cc9372d752d8488e6505b"

exporter:
  requeueMaxJitterPercent: 10
  vulnerabilityReports:
    targetLabels:
      # - image_namespace
      # - image_repository
      # - image_tag
      # - vulnerability_id
  CISKubeBenchReports:
    targetLabels:
      # - test_number
      # - test_desc
      # - test_status

monitoring:
  serviceMonitor:
    enabled: true
    labels: {}

  grafanaDashboard:
    enabled: true
    namespace: "monitoring"

psp:
  enabled: true

networkpolicy:
  enabled: true

podAnnotations: {}