apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  linkerd.io/inject: enabled

commonLabels:
  app: metallb
  tier: infrastructure

resources:
  - github.com/metallb/metallb//manifests?ref=v0.13.4
  - configmap.yaml

patchesStrategicMerge:
  - patches/resource-limits.yaml
