apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  linkerd.io/inject: enabled

commonLabels:
  tier: infrastructure

bases:
  - https://raw.githubusercontent.com/metallb/metallb/v0.12.1/manifests/namespace.yaml
  - https://raw.githubusercontent.com/metallb/metallb/v0.12.1/manifests/metallb.yaml

resources:
  - configmap.yaml

patchesStrategicMerge:
  - patches/resource-limits.yaml
