---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./k8s/cluster/overlays/local
  prune: true
  sourceRef:
    kind: GitRepository
    name: git-repo
