name: Test Cluster Deployment

on:

  workflow_dispatch:
    inputs:
      cleanup:
        description: 'Teardown Kind cluster after workflow run'
        required: false
        default: false
        type: boolean

jobs:

  test:
    runs-on: self-hosted
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup CLI tools
        run: |
          ./scripts/install-cli-tools.sh

      - name: Setup Kubernetes
        run: |
          if [ ! $(kind get clusters --quiet) ]; then
            kind create cluster --config kind-config.yaml --name ci-kind
            kubectl wait node --all --for condition=ready
          fi
          kubectl cluster-info

      - name: Pre-Install Checks
        run: |
          flux check --pre

      - name: Install Flux
        run: |
          flux install

      - name: Post-Install Checks
        run: |
          flux check

      - name: Install Root Kustomization (flux-system)
        run: |
          kubectl apply -k ./k8s/cluster/overlays/local -n flux-system

      - name: Reconcile flux-system
        run: |
          flux reconcile kustomization -n flux-system flux-system --timeout 10m

      - name: Expose services
        run: |
          ./scripts/port-forward.sh

      - name: DAST (Kubescape)
        run: |
          kubescape scan --exclude-namespaces kube-system,kube-public,kube-node-lease,local-path-storage,litmus

      - name: Cluster Configuration (Popeye)
        run: |
          popeye --all-namespaces --lint warn --force-exit-zero

      - name: Login to k6 cloud
        run: |
          k6 login cloud -t $K6_TOKEN
        env:
          K6_TOKEN: ${{ secrets.K6_TOKEN }}

      - name: Run k6 local smoke test
        uses: grafana/k6-action@8203a111fe9500ab659601e28e944296bb646b8d
        with:
          filename: ./test/cluster-smoke-test.js

      - name: Security Scanner (Trivy)
        run: |
          trivy k8s --report summary cluster

      - name: Dump Flux state
        if: failure()
        run: |
          ./scripts/dump-flux-state.sh

      - name: Teardown cluster
        if: inputs.cleanup
        run: |
          kind delete cluster --name ci-kind
