name: Test Cluster Deployment

on:

  workflow_dispatch:

jobs:

  test:
    runs-on: self-hosted
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup CLI tools
        run: |
          ./scripts/install-cli-tools.sh

      - name: Setup Kubernetes
        run: |
          kind create cluster --config kind-config.yaml --name ci-kind
          kubectl wait node --all --for condition=ready
          kubectl cluster-info

      - name: Run pre-installation checks
        run: |
          flux check --pre

      - name: Bootstrap Flux
        run: |
          flux bootstrap github \
            --owner=$GITHUB_USER \
            --repository=${REPOSITORY} \
            --branch=${GITHUB_REF#refs/heads/} \
            --path=./cluster \
            --personal
        env:
          GITHUB_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.FLUX_TOKEN }}
          REPOSITORY: ${{ github.event.repository.name }}

      - name: Reconcile flux-system
        run: |
          flux reconcile kustomization flux-system --with-source
          ./scripts/wait-for-sync.sh

      - name: Expose services
        run: |
          ./scripts/port-forward.sh

      - name: Check configuration
        run: |
          popeye --all-namespaces --lint warn --force-exit-zero

      - name: Run tests
        run: |
          k6 login cloud -t $K6_TOKEN
          k6 run -o cloud ./test/cluster-smoke-test.js
        env:
          K6_TOKEN: ${{ secrets.K6_TOKEN }}

      - name: DAST (Kubescape)
        run: |
          kubescape scan --exclude-namespaces kube-system,kube-public,kube-node-lease,local-path-storage,litmus

      - name: Security Scanner (Trivy)
        run: |
          trivy k8s --report summary cluster

      - name: Dump Flux state
        if: always()
        run: |
          ./scripts/dump-flux-state.sh

      - name: Teardown cluster
        if: always()
        run: |
          kind delete cluster --name ci-kind
