name: Test Cluster Deployment

on:

  workflow_dispatch:
    inputs:
      cleanup:
        description: 'Teardown Kind cluster after workflow run'
        required: false
        default: false
        type: boolean

jobs:

  test:
    runs-on: self-hosted
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@main

      - name: Setup CLI tools
        run: |
          ./scripts/install-cli-tools.sh

      - name: Setup Kubernetes
        run: |
          if [ ! $(kind get clusters --quiet) ]; then
            kind create cluster --config kind-config.yaml --name kind
            kubectl wait node --all --for condition=ready
          fi
          kubectl cluster-info
          docker network inspect -f '{{json .IPAM.Config}}' kind

      - name: Pre-Install Checks
        run: |
          flux check --pre

      - name: Install Flux
        run: |
          flux install

      - name: Post-Install Checks
        run: |
          flux check

      - name: Apply flux-system kustomization
        run: |
          kubectl apply -k ./k8s/cluster/flux-system -n flux-system

      - name: Reconcile flux-system
        run: |
          flux reconcile kustomization -n flux-system flux-system --with-source --timeout 10m

      - name: Wait for sync to complete
        run: |
          ./scripts/wait-for-sync.sh

      - name: Expose services
        run: |
          ./scripts/port-forward.sh

      - name: Build the local manifests as they were built on the cluster
        run: |
          flux build kustomization flux-system --path ./k8s > ./.output/kustomize.yaml

      - name: Upload YAML output
        uses: actions/upload-artifact@v4
        with:
          name: kustomize
          path: ./.output/kustomize.yaml

      - name: DAST (Kubescape)
        run: |
          brew install kubescape
          kubescape scan --exclude-namespaces kube-system,kube-public,kube-node-lease,local-path-storage,litmus

      # - name: Cluster Configuration (Popeye)
      #   run: |
      #     popeye --all-namespaces --lint warn --force-exit-zero

      - name: Login to k6 cloud
        run: |
          k6 login cloud -t $K6_TOKEN
        env:
          K6_TOKEN: ${{ secrets.K6_TOKEN }}

      - name: Run k6 local smoke test
        uses: grafana/k6-action@655099b3d4b0a2b748f84e9e0811616617f8bbc5
        with:
          filename: ./test/cluster-smoke-test.js

      - name: Security Scanner (Trivy)
        run: |
          brew install aquasecurity/trivy/trivy
          trivy k8s --report summary cluster

      - name: Dump Flux state
        if: failure()
        run: |
          ./scripts/dump-flux-state.sh

      - name: Teardown cluster
        if: inputs.cleanup
        run: |
          kind delete cluster --name ci-kind
