name: Dynamic Analysis

on:

  workflow_dispatch:

jobs:

  kubernetes:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup CLI tools
        run: |
          brew install fluxcd/tap/flux
        env:
          HOMEBREW_NO_INSTALL_CLEANUP: true

      - name: Setup Kubernetes
        run: |
          kind create cluster
          kubectl wait node --all --for condition=ready
          kubectl cluster-info

      - name: Run pre-installation checks
        run: |
          flux check --pre

      - name: Bootstrap Flux
        run: |
          flux bootstrap github \
            --owner=$GITHUB_USER \
            --repository=${REPOSITORY} \
            --branch=${GITHUB_REF#refs/heads/} \
            --path=./cluster \
            --personal
        env:
          GITHUB_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.FLUX_TOKEN }}
          REPOSITORY: ${{ github.event.repository.name }}

      - name: Reconcile flux-system
        run: |
          flux reconcile kustomization flux-system --with-source

      - name: Expose services
        run: |
          ./scripts/port-forward.sh

      - name: Test
        run: |
          echo "Run K6 Tests ... "

      - name: DAST (Kubescape)
        run: |
          kubescape scan --exclude-namespaces kube-system,kube-public,kube-node-lease,local-path-storage,litmus

      - name: Debug failure
        if: failure()
        run: |
          kubectl get ns
          kubectl get crd
          kubectl -n flux-system get all
          kubectl -n flux-system logs deploy/source-controller
          kubectl -n flux-system logs deploy/kustomize-controller
          kubectl -n flux-system logs deploy/helm-controller
