name: Dynamic Analysis

on:

  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup CLI tools
        run: |
          ./scripts/install-cli-tools.sh

      - name: Setup Kubernetes
        run: |
          kind create cluster --config kind-config.yaml --name ci-kind
          kubectl wait node --all --for condition=ready
          kubectl cluster-info

      - name: Run pre-installation checks
        run: |
          flux check --pre

      - name: Bootstrap Flux
        run: |
          flux bootstrap github \
            --owner=$GITHUB_USER \
            --repository=${REPOSITORY} \
            --branch=${GITHUB_REF#refs/heads/} \
            --path=./cluster \
            --personal
        env:
          GITHUB_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.FLUX_TOKEN }}
          REPOSITORY: ${{ github.event.repository.name }}

      - name: Reconcile flux-system
        run: |
          flux reconcile kustomization flux-system --with-source

      - name: Expose services
        run: |
          ./scripts/port-forward.sh || ./scripts/debug-failure.sh

      - name: Check configuration
        run: |
          popeye --all-namespaces --lint warn

      - name: Run tests
        run: |
          k6 run test.js

      - name: DAST (Kubescape)
        run: |
          kubescape scan --exclude-namespaces kube-system,kube-public,kube-node-lease,local-path-storage,litmus

      - name: Debug failure
        if: failure()
        run: |
          ./scripts/debug-failure.sh

      - name: Teardown cluster
        if: always()
        run: |
          kind delete cluster --name ci-kind