name: Dynamic Analysis

on:

  workflow_dispatch:

jobs:

  run-test:
    name: Flux Sync
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v1

    - name: Run install script
      env:
        GITHUB_USER: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.FLUX_TOKEN }}
      run: |
        ./install.sh

    - name: Docker network checks
      run: |
        docker network inspect -f '{{.IPAM.Config}}' kind

    - name: Namespace checks
      run: |
        ns=( \
          "flux-system"
        )

        for i in "${ns[@]}"
        do
          kubectl get ns "${i}"
        done
