name: e2e

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - '*'

jobs:
  kubernetes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@main

      - name: Setup Kubernetes Kind
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.14.0"
          config: kind-config.yaml

      - name: Cluster Info
        run: |
          kubectl cluster-info
          kubectl get pods -n kube-system

      - name: Network Info
        run: |
          docker network list
          docker network inspect -f '{{json .IPAM.Config}}' kind

      - name: Pre-Install Checks
        run: |
          flux check --pre

      - name: Install Flux
        run: |
          kubectl apply -f ./k8s/cluster/flux-system/gotk-components.yaml

      - name: Apply flux-system kustomization
        run: |
          kubectl apply -k ./k8s/cluster/flux-system

      - name: Reconcile flux-system
        run: |
          flux reconcile kustomization -n flux-system flux-system --with-source --timeout 10m

      - name: Post-Install Checks
        run: |
          flux check

      - name: Wait for sync to complete
        run: |
          ./scripts/wait-for-sync.sh

      - name: Expose services
        run: |
          ./scripts/port-forward.sh

      - name: Build the local manifests as they were built on the cluster
        run: |
          flux build kustomization flux-system --path ./k8s > ./.output/kustomize.yaml

      - name: Upload YAML output
        uses: actions/upload-artifact@v3
        with:
          name: kustomize
          path: ./.output/kustomize.yaml

      - name: Dump Flux state
        if: failure()
        run: |
          ./scripts/dump-flux-state.sh

