name: sast-apps

on:
  push:
    branches: [ main ]
    paths:
      - 'k8s/apps/**'
      - '!k8s/apps/**/*.md'

  workflow_dispatch:

jobs:

  kustomize:
    name: Kustomize YAML
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate kustomize YAML
        run: kustomize build ./k8s/apps > ./.output/kustomize.yaml

      - name: Upload YAML output
        uses: actions/upload-artifact@v2
        with:
          name: kustomize
          path: ./.output/kustomize.yaml

  kubescape:
    name: Kubescape
    needs: kustomize
    runs-on: ubuntu-latest

    steps:
      - name: Install Kubescape
        run: curl -s https://raw.githubusercontent.com/armosec/kubescape/master/install.sh | /bin/bash

      - name: Download Kustomize YAML
        uses: actions/download-artifact@v2
        with:
          name: kustomize

      - name: Kubescape scan
        run: kubescape scan framework all kustomize.yaml --verbose --fail-threshold 0 --exclude-namespaces kube-system,kube-public

  kube-score:
    name: kube-score
    needs: kustomize
    runs-on: ubuntu-latest

    steps:
      - name: Setup kube-score
        uses: tobbbles/setup-kubescore@v1.0.2
        with:
          version: latest

      - name: Download manifest
        uses: actions/download-artifact@v2
        with:
          name: kustomize

      - name: Calculate kube-score score
        run: kube-score score kustomize.yaml --ignore-container-cpu-limit --ignore-container-memory-limit
