apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 10m0s
  targetNamespace: ingress-nginx
  chart:
    spec:
      chart: ingress-nginx
      version: "4.1.1"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      valuesFiles:
        - values.yaml
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
