apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml
  # - resource

patchesStrategicMerge:
  - patches/resource-limits.yaml
  - patches/inject-linkerd.yaml

namespace: ingress-nginx
