apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  linkerd.io/inject: enabled

commonLabels:
  app: metrics-server
  tier: infrastructure

resources:
  - https://github.com/kubernetes-sigs/metrics-server/releases/download/metrics-server-helm-chart-3.8.2/components.yaml

patchesStrategicMerge:
  - patches/resource-limits.yaml
  - patches/metric-server-insecure-tls.yaml
