---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: finalizers
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./infrastructure/finalizers
  dependsOn:
    - name: metallb
    # - name: ingress-nginx ... HelmRelease
    - name: monitoring-stack
    - name: monitoring-config
    - name: gatekeeper-policy-constraints
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client